// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQJmVGGvINJBGiQwU18jjOWiVDunbQgvQ',
    appId: '1:941001719213:web:8757cc3ed449a984853524',
    messagingSenderId: '941001719213',
    projectId: 'flutter-chat-app-5382e',
    authDomain: 'flutter-chat-app-5382e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5382e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxBW6StQcRst_hlJp-7DIYRcDPR3di6jU',
    appId: '1:941001719213:android:17d59f02a03fda16853524',
    messagingSenderId: '941001719213',
    projectId: 'flutter-chat-app-5382e',
    storageBucket: 'flutter-chat-app-5382e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHbIAdGZiHeGSoVgaVJ3HU8nkx8YRXA5s',
    appId: '1:941001719213:ios:5d233ab6476e0b0b853524',
    messagingSenderId: '941001719213',
    projectId: 'flutter-chat-app-5382e',
    storageBucket: 'flutter-chat-app-5382e.appspot.com',
    iosBundleId: 'com.example.chapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHbIAdGZiHeGSoVgaVJ3HU8nkx8YRXA5s',
    appId: '1:941001719213:ios:f62c5d6db2ccea12853524',
    messagingSenderId: '941001719213',
    projectId: 'flutter-chat-app-5382e',
    storageBucket: 'flutter-chat-app-5382e.appspot.com',
    iosBundleId: 'com.example.chapApp.RunnerTests',
  );
}
